src/dga-design-ref/eServices/Models/ErrorViewModel.cs
namespace eServices.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/dga-design-ref/eServices/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        
        public IActionResult AllRequests()
        {
            return View();
        }public IActionResult EditRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/EParticipationController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
	public class EParticipationController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult ESurveys()
		{
			return View();
		}

		public IActionResult BeneficiaryVoice()
		{
			return View();
		}

		public IActionResult Suggestions()
		{
			return View();
		}

		public IActionResult ContactUs()
		{
			return View();
		}

		public IActionResult OpenDataRequest()
		{
			return View();
		}
	}
}

src/dga-design-ref/eServices/Controllers/ESController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class ESController : Controller
    {
        //  ES (Electronic Summons) Forms الاستدعاء الالكنروني
        public IActionResult StepOne()
        {
            return View();
        }

        public IActionResult StepTwo()
        {
            return View();
        }

        public IActionResult StepThree()
        {
            return View();
        }

        public IActionResult ReviewRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/HomeController.cs
using eServices.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace eServices.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult About()
        {
            return View();
        }
        public IActionResult News(int Id)
        {
            ViewData["NewsId"] = Id;
            return View();
        }

        public IActionResult PrivacyPolicy()
        {
            return View();
        }
    
        public IActionResult TermsAndConditions()
        {
            return View();
        }
        
        public IActionResult PageNotFound()
        {
            return View();
        }

        public IActionResult ServiceLevelAgreement()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/dga-design-ref/eServices/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OTP()
        {
            return View();
        }

        public IActionResult AccountSetup()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/MSController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class MSController : Controller
    {
        // MS (Marriage of Saudi) Forms خدمات الزواج
        public IActionResult StepOne()
        {
            return View();
        }

        public IActionResult StepTwo()
        {
            return View();
        }

        public IActionResult StepThree()
        {
            return View();
        }

        public IActionResult ReviewRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/PRTFController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.Xml;

namespace eServices.Controllers
{
    public class PRTFController : Controller
    {
        // PR-TF (Prisoner Request - Transfer Facility) Forms طلب نقل سجين من سجن لآخر
        public IActionResult StepOne()
        {
            return View();
        }

        public IActionResult StepTwo()
        {
            return View();
        }

        public IActionResult StepThree()
        {
            return View();
        }

        public IActionResult ReviewRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/PRTRController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class PRTRController : Controller
    {
        // PR-TR (Prisoner Request - Temporary Release) Forms طلب الخروج المؤقت للسجين
        public IActionResult StepOne()
        {
            return View();
        }

        public IActionResult StepTwo()
        {
            return View();
        }

        public IActionResult StepThree()
        {
            return View();
        }

        public IActionResult ReviewRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/SharedPRController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;

namespace eServices.Controllers
{
    public class SharedPRController : Controller
    {
        // ND-NS (Non-Deportation Request - Non-Saudi) طلب عدم الإبعاد من المملكة العربية السعودية (لغير السعودي)
        // TR-LR (Travel Request - List Removal) طلب السماح له بالسفر ورفع اسمه من القائمة (للسعودي)
        // RR-RI (Record Removal - Rehabilitation) طلب محو سابقة - رد اعتبار
        // Forms 
        public IActionResult StepOne()
        {
            return View();
        }

        public IActionResult StepTwo()
        {
            return View();
        }

        public IActionResult StepThree()
        {
            return View();
        }

        public IActionResult ReviewRequest()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/TQController.cs
using Microsoft.AspNetCore.Mvc;
using System.Transactions;

namespace eServices.Controllers
{
    public class TQController : Controller
    {
        // TQ (Transaction Query) الاستعلام عن معاملة
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace eServices.Controllers
{
    public class UserController : Controller
    {
        public IActionResult MyProfile()
        {
            return View();
        }

        public IActionResult MyRequests()
        {
            return View();
        }

        public IActionResult RequestDetails()
        {
            return View();
        }
    }
}

src/dga-design-ref/eServices/Views/Admin/Login.cshtml
@{
    ViewData["Title"] = "تسجيل الدخول - ";
}

<div class="pc-img-bg">
    <div class="pc-basic-container pc-sm-container pc-centered-text">
        <div class="pc-basic-container-heading pc-centered-text">
            <h3>تسجيل الدخول لحسابك</h3>
            <p>للدخول إلى بوابة مدير النظام ، يرجى ادخال اسم المستخدم وكلمة المرور</p>
        </div>
        <form action="" id="AdminLoginForm" class="pc-form">
            <div class="pc-input">
                <label for="username" class="pc-input-label"><span class="required">*</span> اسم المستخدم</label>
                <input type="text"
                       id="username"
                       name="username"
                       placeholder="أدخل اسم المستخدم">
                <div class="error"></div>
            </div>
            
            <div class="pc-input">
                <label for="password" class="pc-input-label"><span class="required">*</span> كلمة المرور</label>
                <input type="text"
                       id="password"
                       name="password"
                       placeholder="**********">
                <div class="error"></div>
            </div>
            <button type="submit" class="pc-primary-btn pc-long-btn">
                تسجيل الدخول 
            </button>
        </form>
    </div>
</div>

src/dga-design-ref/eServices/Views/EParticipation/ContactUs.cshtml
@{
    ViewData["Title"] = "تواصل معنا - ";
}

<div class="pc-service-page">
    <div class="pc-service-page-container">
        <div class="pc-service-info">
            <div class="pc-service-info-heading">
                <div class="pc-breadcrumbs">
                    <ul>
                        <li>
                            <a asp-controller="Home" asp-action="Index"> الصفحة الرئيسية </a>
                        </li>
                        <li>></li>
                        <li>
                            <a asp-controller="EParticipation" asp-action="Index"> المشاركة الإلكترونية </a>
                        </li>
                        <li>></li>
                        <li class="pc-breadcrumbs-current">تواصل معنا</li>
                    </ul>
                </div>

                <div class="pc-content-title">
                    <img src="~/icons/palm.svg" alt="palm icon" />
                    <h2>تواصل معنا</h2>
                </div>

                <div class="pc-content-description">
                    <p>
                        يهدف هذا القسم إلى توفير قناة اتصال مباشرة لمستفيدي إمارة منطقة القصيم لضمان تجربة مرضية ولتلبية احتياجاتهم بشكل فعّال.
                    </p>
                </div>
            </div>

            <div class="pc-form-container">
                <div class="form-container">
                    <iframe src='https://forms.zohopublic.sa/customercare/form/Untitled/formperma/1vh2ibnHMNfE4qE5tvuRfFlrZ3v_1tvUGuJZHcJ1JRs'></iframe>
                </div>
            </div>
        </div>

        <div class="pc-info-card">
            <div>
                <h5>قنوات التواصل</h5>

                <div>
                    <div class="pc-text-icon-combo">
                        <img src="~/icons/call.svg" alt="user icon" />
                        <h6>الرقم الموحد</h6>
                    </div>
                    <p>0163231818</p>
                </div>

                <div>
                    <div class="pc-text-icon-combo">
                        <img src="~/icons/mail.svg" alt="clock icon" />
                        <h6>البريد الإلكتروني</h6>
                    </div>
                    <p>info@alqassim.gov.sa</p>
                </div>

                <div>
                    <div class="pc-text-icon-combo">
                        <img src="~/icons/mail.svg" alt="money icon" />
                        <h6>فاكس</h6>
                    </div>
                    <p>00966163249056 - 00966163250619</p>
                </div>

                <div>
                    <div class="pc-text-icon-combo">
                        <img src="~/icons/location.svg" alt="money icon" />
                        <h6>الموقع</h6>
                    </div>
                    <p>القصيم، بريدة، حي الصفراء</p>
                </div>
            </div>

            <svg width="100%" height="1">
                <line x1="0" y1="0" x2="100%" y2="0" stroke="#D2D6DB" stroke-width="2" />
            </svg>

            <div>
                <h5>تابعنا على</h5>
                @* <div class="pc-card-rating">
                </div> *@
                <div class="pc-footer-social-media">
                    <a href="https://www.instagram.com/EmarahAlQassim">
                        <img alt="instagram"
                             src="~/icons/instagramGreen.svg" width="32" height="32" alt="instagram">
                    </a>
                    <a href="https://www.snapchat.com/add/emarahalqassim">
                        <img alt="snapchat"
                             src="~/icons/snapchatGreen.svg" width="32" height="32" alt="snapchat">
                    </a>
                    <a href="https://x.com/EmarahAlQassim">
                        <img alt="x" src="~/icons/xGreen.svg" width="32 alt="x"
                             height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="pc-page-feedback">
        <div>
            <div class="pc-page-feedback-section">
                <p>هل كانت هذه الصفحة مفيدة؟</p>
                <div class="pc-page-feedback-btns">
                    <button class="pc-primary-btn">نعم</button>
                    <button class="pc-primary-btn">لا</button>
                </div>
            </div>
            @* <div class="pc-page-feedback-response">
            <img src="~/icons/checkmarkCircle.svg"/>
            <p>تم إرسال ردك بنجاح</p>
            </div> *@
        </div>
        <div class="pc-page-feedback-section">
            <p class="pc-page-feedback-result">x% من المستخدمين قالوا نعم من x تقييماً</p>
        </div>
    </div>
</div>

src/dga-design-ref/eServices/Views/MS/ReviewRequest.cshtml
@{
    ViewData["Title"] = "مراجعة الطلب - ";
}

<div class="pc-service-steps-page">
    <div class="pc-breadcrumbs">
        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index"> الصفحة الرئيسية </a>
            </li>
            <li>></li>
            <li>
                <a asp-controller="Services" asp-action="Index"> الخدمات</a>
            </li>
            <li>></li>
            <li class="pc-breadcrumbs-current">اسم الخدمة</li>
        </ul>
    </div>

    <div class="pc-service-steps-container">
        <div class="pc-service-steps-progress">
            <div class="pc-step active">
                <div class="pc-step-completed">
                    <img src="~/icons/tick.svg" alt="tick" />
                </div>
                <div class="label">
                    <h6>الخطوة الأولى</h6>
                    <p>تعبئة نموذج الطلب</p>
                </div>
            </div>

            <div class="pc-step-line"></div>

            <div class="pc-step active">
                <div class="pc-step-completed">
                    <img src="~/icons/tick.svg" alt="tick" />
                </div>
                <div class="label">
                    <h6>الخطوة الثانية</h6>
                    <p>إرفاق المستندات</p>
                </div>
            </div>

            <div class="pc-step-line"></div>

            <div class="pc-step active">
                <div class="pc-step-circle">3</div>
                <div class="label">
                    <h6>الخطوة الثالثة</h6>
                    <p>مراجعة الطلب</p>
                </div>
            </div>
        </div>

        @* Mobile progress bar *@
        <div class="pc-service-steps-progress-mobile">
            <div class="progress-circle">
                <img src="~/icons/step1of4.svg" alt="progress" />
            </div>
            <div class="text-section">
                <h5>الخطوة الأولى</h5>
                <p>تعبئة نموذج الطلب</p>
                <p class="next-step">التالي: إرفاق المستندات</p>
            </div>
        </div>

        <div class="pc-service-form pc-basic-container">
            @* بيانات مقدم الطلب *@
            <div class="pc-service-form-heading">
                <h3>طلب الخروج المؤقت للسجين</h3>
                <p>طلب يتقدم به قريب السجين يلتمس فيه خروج السجين اضطرارياً</p>

                <div class="pc-form-line"></div>

                <h4>بيانات مقدم الطلب</h4>
            </div>

            <form action="" method="" id="" class="pc-form">
                <div class="pc-form-grid-2col">
                    <div class="pc-full-width-input">
                        <div class="pc-input">
                            <label for="applicantRole" class="pc-input-label">صفة مقدم الطلب</label>
                            <input type="text" id="applicantRole" name="applicantRole" class="pc-review-input pc-full-width-input" value="وكيل" readonly>
                        </div>
                    </div>

                    <div class="pc-input">
                        <label for="name" class="pc-input-label">الاسم الرباعي</label>
                        <input type="text" id="name" name="name" class="pc-auto-filled-input" value="عبدالله احمد محمد الأحمد" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="nationality" class="pc-input-label">الجنسية</label>
                        <input type="text" id="nationality" name="nationality" class="pc-auto-filled-input" value="المملكة العربية السعودية" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="idNumber" class="pc-input-label">رقم الهوية</label>
                        <input type="text" id="idNumber" name="idNumber" class="pc-auto-filled-input" value="1109882374" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="birthdate" class="pc-input-label">تاريخ الميلاد</label>
                        <input type="text" id="birthdate" name="birthdate" class="pc-auto-filled-input" value="1998-05-19" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="phone" class="pc-input-label"> رقم الجوال</label>
                        <input type="text" id="phone" name="phone" value="0555555555" class="pc-review-input" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="email" class="pc-input-label">البريد الإلكتروني</label>
                        <input type="text" id="email" name="email" value="example@mail.com" class="pc-review-input" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="city" class="pc-input-label">المدينة</label>
                        <input type="text" id="city" name="city" class="pc-auto-filled-input" value="بريدة" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من البريد السعودي</span>
                    </div>

                    <div class="pc-input">
                        <label for="district" class="pc-input-label">الحي</label>
                        <input type="text" id="district" name="district" class="pc-auto-filled-input" value="حي الصفراء" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من البريد السعودي</span>
                    </div>
                </div>
            </form>

            @* بيانات المعني بالطلب *@
            <div class="pc-service-form-heading">
                <div class="pc-form-line"></div>

                <h4>بيانات المعني بالطلب</h4>
            </div>

            <form action="" method="" id="" class="pc-form">
                <div class="pc-form-grid-2col">
                    <div class="pc-input">
                        <label for="name" class="pc-input-label">الاسم الرباعي</label>
                        <input type="text" id="name" name="name" class="pc-review-input" value="عبدالله احمد محمد الأحمد" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="nationality" class="pc-input-label">الجنسية</label>
                        <input type="text" id="nationality" name="nationality" class="pc-review-input" value="المملكة العربية السعودية" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="idNumber" class="pc-input-label">رقم الهوية</label>
                        <input type="text" id="idNumber" name="idNumber" class="pc-review-input" value="1109882374" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="birthdate" class="pc-input-label">تاريخ الميلاد</label>
                        <input type="text" id="birthdate" name="birthdate" class="pc-review-input" value="1998-05-19" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="phone" class="pc-input-label"> رقم الجوال</label>
                        <input type="text" id="phone" name="phone" class="pc-review-input" value="0555555555" readonly>
                        <div class="error"></div>
                    </div>

                    <div class="pc-input">
                        <label for="email" class="pc-input-label">البريد الإلكتروني</label>
                        <input type="text" id="email" name="email" class="pc-review-input" value="example@mail.com" readonly>
                        <div class="error"></div>
                    </div>

                    <div class="pc-input">
                        <label for="city" class="pc-input-label">المدينة</label>
                        <input type="text" id="city" name="city" class="pc-review-input" value="بريدة" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="district" class="pc-input-label">الحي</label>
                        <input type="text" id="district" name="district" class="pc-review-input" value="حي الصفراء" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="prison" class="pc-input-label">السجن</label>
                        <input type="text" id="prison" name="prison" class="pc-review-input" value="سجن بريدة" readonly>
                    </div>

                    <div class="pc-input">
                        <label for="reason" class="pc-input-label">سبب طلب الخروج المؤقت</label>
                        <input type="text" id="reason" name="reason" class="pc-review-input" value="حضور زواج" readonly>
                    </div>

                    <div class="pc-input pc-full-width-input">
                        <label for="details" class="pc-input-label"> تفاصيل الطلب</label>
                        <textarea name="details" id="details" class="pc-review-input" readonly></textarea>
                    </div>
                </div>
            </form>

            @* المرفقات *@
            <div class="pc-service-form-heading">
                <div class="pc-form-line"></div>

                <h4>المرفقات</h4>
            </div>

            <table class="pc-table pc-striped-table attachments-table">
                <thead>
                    <tr>
                        <th>اسم الملف</th>
                        <th>صيغة الملف</th>
                        <th>حجم الملف</th>
                        <th>معاينة الملف</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>National ID</td>
                        <td>jpg</td>
                        <td>212 KB</td>
                        <td>
                        <button class="pc-outline-btn">
                        معاينة
                        </button>
                        </td>
                    </tr>
                    <tr>
                        <td>صك الحكم</td>
                        <td>png</td>
                        <td>212 KB</td>
                        <td>
                        <button class="pc-outline-btn">
                        معاينة
                        </button>
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="pc-service-form-heading">
                <div class="pc-form-line"></div>
            </div>

            <div class="pc-checkbox-container">
                <label class="pc-accept-terms" for="acceptTerms">
                    <input type="checkbox" id="acceptTerms" name="acceptTerms" class="checkbox-input">
                    <span class="pc-checkbox"></span>
                    <span class="pc-checkbox-text">
                        أقر بأن جميع البيانات صحيحة وأتحمل كامل المسؤولية في حال ثبوت غير ذلك، كما أقر بالموافقة على
                        <a asp-controller="Home" asp-action="TermsAndConditions">الشروط والأحكام</a>
                    </span>
                </label>
                <div class="error"></div>
            </div>

            <div class="pc-form-buttons">
                <a asp-controller="PRTR" asp-action="StepThree" class="pc-outline-btn">رجوع</a>
                <button class="pc-primary-btn" id="sendRequest">إرسال الطلب</button>
            </div>
        </div>
    </div>
</div>

src/dga-design-ref/eServices/Views/MS/StepOne.cshtml
@{
    ViewData["Title"] = "تعبئة نموذج الطلب - ";
}

<div class="pc-service-steps-page">
    <div class="pc-breadcrumbs">
        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index"> الصفحة الرئيسية </a>
            </li>
            <li>></li>
            <li>
                <a asp-controller="Services" asp-action="Index"> الخدمات</a>
            </li>
            <li>></li>
            <li class="pc-breadcrumbs-current">اسم الخدمة</li>
        </ul>
    </div>

    <div class="pc-service-steps-container">
        <div class="pc-service-steps-progress">
            <div class="pc-step active">
                <div class="pc-step-circle">1</div>
                <div class="label">
                    <h6>الخطوة الأولى</h6>
                    <p>تعبئة نموذج الطلب</p>
                </div>
            </div>

            <div class="pc-step-line"></div>

            <div class="pc-step">
                <div class="pc-step-circle">3</div>
                <div class="label">
                    <h6>الخطوة الثانية</h6>
                    <p>إرفاق المستندات</p>
                </div>
            </div>

            <div class="pc-step-line"></div>

            <div class="pc-step">
                <div class="pc-step-circle">4</div>
                <div class="label">
                    <h6>الخطوة الثالثة</h6>
                    <p>مراجعة الطلب</p>
                </div>
            </div>
        </div>

        @* Mobile progress bar *@
        <div class="pc-service-steps-progress-mobile">
            <div class="progress-circle">
                <img src="~/icons/step1of4.svg" alt="progress" />
            </div>
            <div class="text-section">
                <h5>الخطوة الأولى</h5>
                <p>تعبئة نموذج الطلب</p>
                <p class="next-step">التالي: إرفاق المستندات</p>
            </div>
        </div>

        <div class="pc-service-form pc-basic-container">
            <div class="pc-service-form-heading">
                <h3>اسم الخدمة</h3>
                <p>وصف الخدمة</p>

                <div class="pc-form-line"></div>

                <p class="pc-warning-text">* المعلومات المطلوبة</p>
            </div>

            <form action="" method="" id="MS-step1-form" class="pc-form">
                <div class="pc-form-grid-2col">
                    <div class="pc-input">
                        <label for="name" class="pc-input-label">الاسم الرباعي</label>
                        <input type="text" id="name" name="name" class="pc-auto-filled-input" value="عبدالله احمد محمد الأحمد" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="nationality" class="pc-input-label">الجنسية</label>
                        <input type="text" id="nationality" name="nationality" class="pc-auto-filled-input" value="المملكة العربية السعودية" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="idNumber" class="pc-input-label">رقم الهوية</label>
                        <input type="text" id="idNumber" name="idNumber" class="pc-auto-filled-input" value="1109882374" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="birthdate" class="pc-input-label">تاريخ الميلاد</label>
                        <input type="text" id="birthdate" name="birthdate" class="pc-auto-filled-input" value="1998-05-19" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من مركز المعلومات الوطني</span>
                    </div>

                    <div class="pc-input">
                        <label for="phone" class="pc-input-label"> <span class="required">*</span> رقم الجوال</label>
                        <input type="text" id="phone" name="phone" placeholder="05xxxxxxxx">
                        <div class="error"></div>
                    </div>

                    <div class="pc-input">
                        <label for="email" class="pc-input-label">البريد الإلكتروني</label>
                        <input type="text" id="email" name="email" placeholder="example@mail.com">
                        <div class="error"></div>
                    </div>

                    <div class="pc-input">
                        <label for="city" class="pc-input-label">المدينة</label>
                        <input type="text" id="city" name="city" class="pc-auto-filled-input" value="بريدة" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من البريد السعودي</span>
                    </div>

                    <div class="pc-input">
                        <label for="district" class="pc-input-label">الحي</label>
                        <input type="text" id="district" name="district" class="pc-auto-filled-input" value="حي الصفراء" readonly>
                        <span class="pc-service-form-tooltip">تم استرداد المعلومات من البريد السعودي</span>
                    </div>
                </div>

                <div class="pc-input pc-full-width-input">
                    <label for="details" class="pc-input-label"> <span class="required">*</span> تفاصيل الطلب</label>
                    <textarea name="details" id="details" placeholder="الرجاء إيضاح تفاصيل الطلب على ألا يقل عن 30 حرف  "></textarea>
                    <div class="error"></div>
                </div>

                <div class="pc-form-buttons">
                    @* change the asp-route-id="MSNA" to make it dynamic based on the service id*@
                    <a asp-controller="Services" asp-action="AboutTheService" asp-route-id="MSNA" class="pc-outline-btn">إلغاء</a>
                    <button type="submit" class="pc-primary-btn">التالي</button>
                </div>
            </form>
        </div>
    </div>
</div>