src/QassimPrincipality.Web/ViewModels/ShareData/AddShareDataVM.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace QassimPrincipality.Web.ViewModels.ShareData
{
    public class AddShareDataVM
    {
        public string UserFullName { get; set; }
        public string LegalJustificationDescription { get; set; } 
        [Required(ErrorMessage = "أدخل البريد الإلكتروني")]
        public string UserEmail { get; set; }
        [Required(ErrorMessage = "أدخل  الجوال")]
        public string UserMobile { get; set; }
        [Required(ErrorMessage = "أدخل الغرض من طلب البيانات")]
        public string PurposeOfRequest { get; set; }
        [Required(ErrorMessage = "أدخل وصف البيانات المطلوبة")]
        public string Description { get; set; }
        public string IdentityNumber { get; set; }
        public int EntityId { get; set; }
        public bool IsApproved { get; set; }
        [BindProperty, Required(ErrorMessage = "لابد من تحديد هل توجد اتفاقية مشاركة البيانات")]
        public string IsShareAgreementExist { get; set; }
        [BindProperty,Required(ErrorMessage = "لابد من تحديد هل توجد بيانات شخصية")]
        public string IsContainsPersonalData { get; set; }
        [BindProperty,Required(ErrorMessage = "لابد من تحديد هل مقدم الطلب هو ممثل المكتب")]
        public string IsRequesterDataOfficePresenter { get; set; }
        [BindProperty,Required(ErrorMessage = "لابد من تحديد هل يوجد سند قانوني")]
        public string IsLegalJustification { get; set; }
        public bool IsAllowed { get; set; }
        
    }
}

src/QassimPrincipality.Web/Controllers/RequestsAdminController.cs
using Framework.Core.AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using QassimPrincipality.Application.Lookups.Attachments;
using QassimPrincipality.Application.Services.Lookups.Main.RequestType;
using QassimPrincipality.Application.Services.Main.UploadRequest;
using QassimPrincipality.Application.Services.Main.UploadRequest.Dto;
using static OfficeOpenXml.ExcelErrorValue;

namespace QassimPrincipality.Web.Controllers
{
    public class RequestsAdminController : Controller
    {
        private readonly UploadRequestAppService _uploadRequestService;
        private readonly AttachmentAppService _attachmentAppService;
        private readonly RequestTypeAppService _requestTypeAppService;

        public RequestsAdminController(
            UploadRequestAppService uploadRequestAppService,
            RequestTypeAppService requestTypeAppService,
            AttachmentAppService attachmentAppService
        )
        {
            _uploadRequestService = uploadRequestAppService;
            _requestTypeAppService = requestTypeAppService;
            _attachmentAppService = attachmentAppService;
        }
        [Authorize(Roles = "EServicesRequestAdmin,Admin")]

        public async Task<IActionResult> RequestList(string type, int page = 1)
        {
            bool? status = null;
            bool? isPending = null;
            switch (type)
            {
                case "1":
                    status = true;
                    break;
                case "0":
                    status = false;
                    break;
                case "2":
                    status = null;
                    isPending = true;
                    break;
                default:
                    status = null;
                    type = "20";
                    break;
            }

            var lst = new List<object>
            {
                new {Id = "0",Name="طلبات منتهية بالرفض"},
                new {Id = "1",Name="طلبات منتهية بالموافقة"},
                new {Id = "2",Name="طلبات قيد الإجراء"},
                new {Id = "20",Name="كل الطلبات"},
            };
            ViewBag.items = new SelectList(lst, "Id", "Name", type);

            ViewBag.status = type;
            var result = await _uploadRequestService.SearchAsync(
                new UploadRequestSearchDto()
                {
                    isPending = isPending,
                    IsApproved = status,
                    PageNumber = page,
                    PageSize = 10
                }
            );
            return View(result);
        }
        [Authorize]

        public async Task<IActionResult> Details(string requestId)
        {
            var result = await _uploadRequestService.GetById(Guid.Parse(requestId));

            return View(result);
        }

        [HttpGet]
        [Authorize]

        public async Task<IActionResult> Download(Guid id)
        {
            // Fetch the file information from your data store
            var file = await _attachmentAppService.GetAttachmentForDownload(id);

            if (file == null)
                return NotFound();

            // Return the file using a FileResult
            return File(file.AttachmentContent.FileContent, file.ContentType, file.FileName);
        }
        [HttpPost]
        [Authorize(Roles = "EServicesRequestAdmin,Admin")]

        public async Task<IActionResult> Accept(string requestId)
        {
            await _uploadRequestService.AcceptOrReject(Guid.Parse(requestId), true);
            return RedirectToAction("Details", new { requestId });
        }
        [HttpPost]
        [Authorize(Roles = "EServicesRequestAdmin,Admin")]
        public async Task<IActionResult> Reject(string requestId, string rejectReasons)
        {
            await _uploadRequestService.AcceptOrReject(Guid.Parse(requestId), false, rejectReasons);
            return RedirectToAction("Details", new { requestId });
        }
        // [HttpGet]
        //public async Task<IActionResult> Users(int? page, string search)
        //{
        //    ViewBag.Search = search;
        //    List<UserIdentity> resultList = new List<UserIdentity>();
        //    var extenalEntities = await _externalEntityService.GetExternalEntityAsync();
        //    System.Security.Claims.Claim result = GetCurrentUserClaimRelatedToExternalEntity(
        //        extenalEntities
        //    );
        //    ExternalEntityDto currentEntity = null;

        //    if (result != null)
        //    {
        //        resultList = (List<UserIdentity>)await _userManager.GetUsersForClaimAsync(result);
        //        currentEntity = extenalEntities.FirstOrDefault(c => c.ClaimValue == result.Value);
        //    }
        //    ExternalEntityUsersDto usersEntities = new ExternalEntityUsersDto
        //    {
        //        TotalCount = 0,
        //        PageSize = 10,
        //        Users = new List<UserExternalEntityDto>()
        //    };
        //    var email = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
        //    resultList = resultList
        //        .Where(c => c.Id != email)
        //        .Where(c => string.IsNullOrEmpty(search) || c.Email.Contains(search))
        //        ?.ToList();

        //    if (resultList?.Any() ?? false)
        //    {
        //        var admins = await _userManager.GetUsersInRoleAsync("OwningEntityAdmin");
        //        var pms = await _userManager.GetUsersInRoleAsync("OwnerProjectManager");
        //        var entry = await _userManager.GetUsersInRoleAsync("OwningEntity");
        //        var users = entry
        //            .Where(c => !pms.Any(p => p.UserName == c.UserName))
        //            .Where(c => !admins.Any(p => p.UserName == c.UserName))
        //            //  .Select(c => c.Id.ToString())
        //            .ToArray();

        //        string[] userIds = users.Select(c => c.Id.ToString()).ToArray();
        //        resultList = resultList.Where(c => userIds.Contains(c.Id)).ToList();

        //        usersEntities = await _userExternalEntityService.GetUsersExternalEntityAsync(
        //            page.HasValue ? page.Value - 1 : 0,
        //            resultList.Select(c => c.Id).ToArray()
        //        );
        //        foreach (var item in usersEntities.Users)
        //        {
        //            var u = resultList.FirstOrDefault(c => c.Id == item.UserId);
        //            var user = users.FirstOrDefault(c => c.Id.ToString() == u.Id);
        //            var claims = await _userManager.GetClaimsAsync(user);

        //            item.ExternalEntity = currentEntity;
        //            item.Email = user?.Email;
        //            item.PhoneNumber = user?.PhoneNumber;
        //            item.UserName =
        //                claims?.FirstOrDefault(c => c.Type == "given_name")?.Value
        //                ?? user?.UserName;
        //        }

        //        if (usersEntities.Users.Any(c => c.SubExternalEntityId != null))
        //        {
        //            var entities = await _subExternalEntityService.GetSubExternalEntityByIdsAsync(
        //                usersEntities.Users.Select(c => c.SubExternalEntityId).ToArray()
        //            );

        //            foreach (var item in usersEntities.Users)
        //            {
        //                item.SubExternalEntity =
        //                    entities.FirstOrDefault(c => c.Id == item.SubExternalEntityId) ?? null;
        //            }
        //        }
        //    }

        //    return View(usersEntities);
        //}
    }
}

src/QassimPrincipality.Web/Controllers/ShareDataController.cs
using System.Globalization;
using Framework.Core.Extensions;
using Framework.Identity.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using QassimPrincipality.Application.Services.Main.Contact;
using QassimPrincipality.Application.Services.Main.OpenData;
using QassimPrincipality.Application.Services.Main.ShareData;
using QassimPrincipality.Application.Services.Main.ShareDataRequest;
using QassimPrincipality.Application.Services.NewShema;
using QassimPrincipality.Domain.Entities.Services.Main;
using QassimPrincipality.Web.Helpers;
using QassimPrincipality.Web.ViewModels.Contact;
using QassimPrincipality.Web.ViewModels.OpenData;
using QassimPrincipality.Web.ViewModels.ShareData;

namespace QassimPrincipality.Web.Controllers
{
    [Authorize]
    public class ShareDataController : Controller
    {
        private readonly ShareDataAppService _shareDataService;
        private readonly LookupAppService _lookUpService;
        private readonly UserAppService _userAppService;
        private readonly ReferralNumberConfiguration _referralNumberConfiguration;

        public ShareDataController(
            ShareDataAppService shareDataService,
            LookupAppService lookUpService,
            UserAppService userAppService,
            IOptions<ReferralNumberConfiguration> referralNumberConfiguration
        )
        {
            _shareDataService = shareDataService;
            _lookUpService = lookUpService;
            _userAppService = userAppService;
            _referralNumberConfiguration = referralNumberConfiguration.Value;
        }

        public async Task<IActionResult> Index(string type, int page = 1)
        {
            bool? status = null;
            bool? isPending = null;
            switch (type)
            {
                case "1":
                    status = true;
                    break;
                case "0":
                    status = false;
                    break;
                case "2":
                    status = null;
                    isPending = true;
                    break;
                default:
                    status = null;
                    type = "20";
                    break;
            }

            var lst = new List<object>
            {
                new { Id = "0", Name = "طلبات منتهية بالرفض" },
                new { Id = "1", Name = "طلبات منتهية بالموافقة" },
                new { Id = "2", Name = "طلبات قيد الإجراء" },
                new { Id = "20", Name = "كل الطلبات" },
            };
            ViewBag.items = new SelectList(lst, "Id", "Name", type);

            ViewBag.status = type;
            var result = await _shareDataService.SearchAsync(
                new ShareDataRequestSearchDto()
                {
                    // IsPending = isPending,
                    IsApproved = status,
                    PageNumber = page,
                    PageSize = 10,
                    // CreatedBy = HttpContext.User.GetId()
                }
            );
            return View(result);
        }

        public async Task<ActionResult> Create()
        {
            AddShareDataVM vM = new AddShareDataVM();
            var user = await _userAppService.GetUserAsync(Guid.Parse(HttpContext.User.GetId()));
            vM.UserFullName = user.FullNameAr ?? user.FullName;
            vM.IdentityNumber = "1234567899";
            vM.LegalJustificationDescription = "وصف المسوغ القانوني";
            ViewData["entities"] = (await _lookUpService.GetEntities())
                .Select(c => new SelectListItem
                {
                    Text = CultureInfo.CurrentCulture.Name == "en-US" ? c.NameEn : c.NameAr,
                    Value = c.Id.ToString(),
                })
                .ToList();
            return View(vM);
        }

        // POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddShareDataVM model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["entities"] = (await _lookUpService.GetEntities())
                    .Select(c => new SelectListItem
                    {
                        Text = CultureInfo.CurrentCulture.Name == "en-US" ? c.NameEn : c.NameAr,
                        Value = c.Id.ToString(),
                    })
                    .ToList();
                return View(model);
            }
            ShareDataDto dto = new ShareDataDto();
            dto.PurposeOfRequest = model.PurposeOfRequest;
            dto.Description = model.Description;
            dto.UserEmail = model.UserEmail;
            dto.UserMobile = model.UserMobile;
            dto.IdentityNumber = model.IdentityNumber;
            dto.UserFullName = model.UserFullName;
            dto.EntityTypeId = model.EntityId;
            dto.IsLegalJustification = model.IsLegalJustification == "true" ? true : false;
            dto.LegalJustificationDescription = model.LegalJustificationDescription;
            dto.IsRequesterDataOfficePresenter =
                model.IsRequesterDataOfficePresenter == "true" ? true : false;
            ;
            dto.IsContainsPersonalData = model.IsContainsPersonalData == "true" ? true : false;
            dto.IsShareAgreementExist = model.IsShareAgreementExist == "true" ? true : false;
            // dto.IsApproved = null;
            //dto.CreatedBy = HttpContext.User.GetId();

            // dto.ReferralNumber = _referralNumberConfiguration.ShareDataStart
            // + DateTime.Now.ToString("yyMMddHHmmss");
            var req = await _shareDataService.InsertAsync(dto);
            return RedirectToAction(
                "Index",
                "Common",
                new
                {
                    SuccessMessage = "تم حفظ بيانات الطلب بنجاح",
                    // requestNumber = req.ReferralNumber
                }
            );
        }

        [Authorize(Roles = "ShareDataRequestAdmin,Admin")]
        public async Task<IActionResult> RequestList(string type, int page = 1)
        {
            bool? status = null;
            bool? isPending = null;
            switch (type)
            {
                case "1":
                    status = true;
                    break;
                case "0":
                    status = false;
                    break;
                case "2":
                    status = null;
                    isPending = true;
                    break;
                default:
                    status = null;
                    type = "20";
                    break;
            }

            var lst = new List<object>
            {
                new { Id = "0", Name = "طلبات منتهية بالرفض" },
                new { Id = "1", Name = "طلبات منتهية بالموافقة" },
                new { Id = "2", Name = "طلبات قيد الإجراء" },
                new { Id = "20", Name = "كل الطلبات" },
            };

            ViewBag.items = new SelectList(lst, "Id", "Name", type);
            ViewBag.status = type;
            var result = await _shareDataService.SearchAsync(
                new ShareDataRequestSearchDto()
                {
                    IsApproved = status,
                    PageNumber = page,
                    PageSize = 10,
                    //IsPending = isPending
                }
            );
            return View(result);
        }

        public async Task<IActionResult> Details(string requestId)
        {
            var result = await _shareDataService.GetById(Guid.Parse(requestId));

            return View(result);
        }

        [Authorize(Roles = "ShareDataRequestAdmin,Admin")]
        public async Task<IActionResult> Accept(string requestId)
        {
            //await _shareDataService.AcceptOrReject(Guid.Parse(requestId), true);
            return RedirectToAction("Details", new { requestId });
        }

        [HttpPost]
        [Authorize(Roles = "ShareDataRequestAdmin,Admin")]
        public async Task<IActionResult> Reject(string requestId, string rejectReasons)
        {
            //await _shareDataService.AcceptOrReject(Guid.Parse(requestId), false, rejectReasons);
            return RedirectToAction("Details", new { requestId });
        }
    }
}

src/QassimPrincipality.Web/Views/ShareData/Create.cshtml
@using QassimPrincipality.Web.ViewModels.ShareData
@model AddShareDataVM


<div class="share-data">
    <div id="requestContent" class="row justify-content-xxl-center">
        <div class="col-xxl-10">
            <div class="page-panel box-panel">
                <h3 class="page-title box-title text-center">طلب مشاركة البيانات</h3>
                <form id="client-form" class="form" asp-controller="ShareData" asp-action="Create" Method="post">
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="UserFullName">
                                    اسم
                                </label>
                                <input type="text" class="form-control" readonly asp-for="UserFullName">
                                <span asp-validation-for="UserFullName" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="UserEmail">
                                    البريد إلكتروني
                                </label>
                                <input type="text" class="form-control" asp-for="UserEmail" maxlength="50">
                                <span asp-validation-for="UserEmail" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="IdentityNumber">
                                    رقم الهوية / الإقامة
                                </label>
                                <input type="text" class="form-control" maxlength="10" asp-for="IdentityNumber">
                                <span asp-validation-for="IdentityNumber" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="UserMobile">
                                    رقم الجوال
                                </label>

                                <input type="text" class="form-control" asp-for="UserMobile" maxlength="14">
                                <span asp-validation-for="UserMobile" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>
                        @if (ViewData["entities"] != null)
                        {
                            var entities = (List<SelectListItem>)ViewData["entities"];
                            <div class="col-xl-6">
                                <div id="RequestType" class="form-group mt-3">
                                    <label asp-for="EntityId" class="form-label">
                                        نوع الجهة
                                    </label>

                                    <select asp-for="EntityId" required asp-items="@(new SelectList(entities, "Value", "Text"))"
                                            class="form-control" id="ddlentityTypes">
                                    </select>
                                    <span asp-validation-for="EntityId" class="text-danger"></span>

                                </div>
                            </div>
                        }
                        <div class="col-xl-6">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="PurposeOfRequest">
                                    الغرض من طلب البيانات
                                </label>
                                <input type="text" class="form-control" asp-for="PurposeOfRequest">
                                <span asp-validation-for="PurposeOfRequest" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>
                        <div class="col-xl-12">
                            <div class="form-group mt-3">
                                <label asp-for="Description" class="form-label">وصف البيانات المطلوبة</label>
                                <textarea asp-for="Description" class="form-control" rows="5" cols="6" maxlength="400"></textarea>
                                <span asp-validation-for="Description" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>


                        <div class="col-xl-12">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="IsShareAgreementExist">هل توجد اتفاقية مشاركة بيانات مسبقاً؟</label>
                                <div class="d-flex gap-3">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" asp-for="IsShareAgreementExist" value="نعم" id="IsShareAgreementExistTrue" />
                                        <label for="IsShareAgreementExistTrue">نعم</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" asp-for="IsShareAgreementExist" value="لا" id="IsShareAgreementExistFalse" />
                                        <label for="IsShareAgreementExistFalse">لا</label>
                                    </div>
                                </div>
                                <span asp-validation-for="IsShareAgreementExist" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>

                        <div class="col-xl-12">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="IsContainsPersonalData">هل تحتوي على بيانات شخصية؟</label>
                                <div class="d-flex gap-3">

                                    <div class="form-check form-check-inline">


                                        <input class="form-check-input" type="radio" asp-for="IsContainsPersonalData" value="نعم" id="IsContainsPersonalDataTrue" />

                                        <label for="IsContainsPersonalDataTrue">نعم</label>
                                    </div>
                                    <div class="form-check form-check-inline">


                                        <input class="form-check-input" type="radio" asp-for="IsContainsPersonalData" value="لا" id="IsContainsPersonalDataFalse" />
                                        <label for="IsContainsPersonalDataFalse">لا</label>
                                    </div>


                                </div>
                                <span asp-validation-for="IsContainsPersonalData" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>


                        <div class="col-xl-12">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="IsRequesterDataOfficePresenter">هل مقدم الطلب هو ممثل مكتب البيانات لدى الجهة؟</label>
                                <div class="d-flex gap-3">

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" asp-for="IsRequesterDataOfficePresenter" value="نعم" id="IsRequesterDataOfficePresenterTrue" />
                                        <label for="IsRequesterDataOfficePresenterTrue">نعم</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" asp-for="IsRequesterDataOfficePresenter" value="لا" id="IsRequesterDataOfficePresenterFalse" />
                                        <label for="IsRequesterDataOfficePresenterFalse">لا</label>
                                    </div>
                                </div>
                                <span asp-validation-for="IsRequesterDataOfficePresenter" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>

                        <div class="col-xl-12">
                            <div class="form-group mt-3">
                                <label class="form-label" asp-for="IsLegalJustification">هل يوجد لدى الجهة مسوغ قانوني لطلب البيانات؟</label>
                                <div class="d-flex gap-3">

                                    <div class="form-check form-check-inline ">
                                        <div class="form-check form-check-inline">


                                            <input class="form-check-input" type="radio" asp-for="IsLegalJustification" value="نعم" id="IsLegalJustificationTrue" />

                                            <label for="IsLegalJustificationTrue">نعم</label>
                                        </div>
                                        <div class="form-check form-check-inline">


                                            <input class="form-check-input" type="radio" asp-for="IsLegalJustification" value="لا" id="IsLegalJustificationFalse" />
                                            <label for="IsLegalJustificationFalse">لا</label>
                                        </div>


                                    </div>
                                </div>
                                <span asp-validation-for="IsLegalJustification" class="field-validation-valid text-danger"> </span>
                            </div>
                        </div>


                        <div class="form-group mt-3" id="divLegalJustificationDescription" style="display:none">
                            <label class="form-label" asp-for="LegalJustificationDescription">وصف المسوغ القانوني</label>

                            <textarea asp-for="LegalJustificationDescription" class="form-control"></textarea>

                        </div>



                        <div class="form-group mt-3">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary text-right">إرسال</button>
                                <a class="btn btn-outline-primary" href="/">الى الخلف</a>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="container-fluid body-content bg-transparent" style="background-image: url('~/../../Images/row.pattern2.png');">
        <script src="/Scripts/jquery.validate.min.js"></script>
        <script src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
        <div class="modal" id="newItemRejectLink" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">تقديم طلب مشاركة بيانات</h5>

                    </div>
                    <div class="modal-body">
                        <div style="text-align:center;color:#a12d00;font-weight:600;">
                            تم إستقبال طلبكم بخصوص مشاركة البيانات  <br> سيتم دراسة المطلوب من قبل المختصين  <br> ويكون الرد عليكم من خلال البريد الإلكتروني المسجل <br> خلال 15 يوم عمل
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" id="btnChangeMobaileNo" data-dismiss="modal" class="btn btn-success" style="width:40%">تم</button>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
       
        
        $(':radio[name=IsLegalJustification]').change(function () {
            // read the value of the selected radio
            var value = $(this).val();
            console.log(value);
            if (value == 'نعم') {
                $('#divLegalJustificationDescription').show();
            }
            else { $('#divLegalJustificationDescription').hide(); }
        });


        // $('#IsLegalJustificationTrue').click(function () {


        //     $("#divLegalJustificationDescription").show();
        // });
        // $('#IsLegalJustificationFalse').click(function () {

        //     $("#divLegalJustificationDescription").hide();

        // });


    });
</script>